# This file provides instructions for packaging.

`PerlX-QuoteOperator-Inescapable`
	perl_version_from m`PerlX::QuoteOperator::Inescapable`;
	version_from      m`PerlX::QuoteOperator::Inescapable`;
	readme_from       m`PerlX::QuoteOperator::Inescapable`;
	requires          p`Data::OptList 0`;
	requires          p`Devel::Declare 0`;
	requires          p`Devel::Declare::Context::Simple 0`;
	requires          p`Sub::Install 0`;
.

