@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/PerlX-QuoteOperator-Inescapable/project>
	deps:runtime-requirement         [ deps:on "Data::OptList 0"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Devel::Declare 0"^^deps:CpanId ];
	deps:runtime-requirement         [
		deps:on "Devel::Declare::Context::Simple 0"^^deps:CpanId;
	];
	deps:runtime-requirement         [ deps:on "Sub::Install 0"^^deps:CpanId ].

