# This file provides instructions for packaging.

`PerlX-QuoteOperator-Inescapable`
	perl_version_from m`PerlX::QuoteOperator::Inescapable`;
	version_from      m`PerlX::QuoteOperator::Inescapable`;
	readme_from       m`PerlX::QuoteOperator::Inescapable`;
	test_requires     p`Test::More 0.61` ;
	.

